config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboards#index'
  resources :users do
    resources :exercises
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :user
  validates :duration_in_min, :workout, :workout_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :exercises

  def full_name
    [first_name, last_name].join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  
  def index
    
  end

end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show]

  def index
    
  end

  def new
    @exercise = current_user.exercises.new
  end

  def show
    
  end

  def create
    @exercise = current_user.exercises.new(exercise_params)
    if @exercise.save
      flash[:notice] = 'Exercise has been created'
      redirect_to [current_user, @exercise]
    else
      flash[:alert] = 'Exercise has not been created!'
      redirect_to new_user_exercise_path
    end
  end


  private

  def exercise_params
    params.require(:exercise).permit(:duration_in_min, :workout, :workout_date, :user_id)
  end

  def set_exercise
    @exercise = current_user.exercises.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/index.html.erb
<div class='container'>
  <div class='wrapper'>
    <h1>Workout Lounge!</h1>
    <p>Show off your workout with your friends and family!</p>
  </div>
</div>

app/views/exercises/_exercise_form.html.erb
  <%= form_for ([current_user, @exercise]) do |f| %>
    
    <%= f.label :duration_in_min, 'Duration (min)' %>
    <%= f.text_field :duration_in_min %>
    <%= f.label :workout, 'Workout details' %>
    <%= f.text_field :workout %>
    <%= f.label :workout_date, 'Activity date' %>
    <%= f.text_field :workout_date %>

    <%= f.submit 'Create Exercise' %>

  <% end %>

app/views/exercises/index.html.erb
<div class="col-md-8 col-xs-12">
  <%= link_to "New Workout", new_user_exercise_path, class: "btn btn-default" %>
</div>

app/views/exercises/new.html.erb
<div>
  <h1>New exercise for <%= "#{current_user.full_name}" %></h1>
  <br />
    <%= render 'exercise_form' %>
    <%= link_to "Back", root_path %>
  <br />
</div>

app/views/exercises/show.html.erb
<div class="col-xs-12 col-md-10 col-md-offset-1">
  <div>
    <h2 class="show-header">
      Showing <%= "#{@exercise.user.full_name}'s Workout Details" %>
    </h2>
  </div>
  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Duration(min)</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.duration_in_min %>
    </div>
    </div>
    
    <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Workout Details</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.workout %>
    </div>
  </div>

  <div class="col-xs-12 col-md-10 well member">
    <div class="col-xs-4">
      <strong>Activity Date</strong>
    </div>
    <div class="col-xs-8 text-right">
      <%= @exercise.workout_date %>
    </div>
  </div>
  <br>
  <br>
  <div class="col-xs-12 col-md-10 member">
    <%= link_to 'Back', user_exercise_path(current_user),
          class: "btn btn-success btn-lg link", id: 'block'%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workouter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'shared/navbar' %>
   <%= render 'shared/notice' %>
   <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
	<nav class="navbar navbar-inverse navbar-fixed-top">
     <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Workouter</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-right">
          <ul class="nav navbar-nav">
           <li> <%= link_to 'Home', root_path %></li>
           <% unless user_signed_in? %>
             <li> <%= link_to 'Sign in', new_user_session_path %></li>
             <li> <%= link_to 'Sign up', new_user_registration_path %></li>
           <% else %>
             <li> <%= link_to 'My Lounge',user_exercises_path(current_user) %></li>
             <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
           <% end %>
           <% if user_signed_in? %>
             <div class="navbar-right">
               <p class="navbar-text">Logged as <%= "#{current_user.email}" %></p>
             </div>
           <% end %>
          </ul>
        </div><!--/.nav-collapse -->
     </div>
   </nav>
  

app/views/shared/_notice.html.erb
    <div class='row'>
       <div class='col-md-12'>
         <% flash.each do |key, message| %>
           <div class="text-center alert alert-<%= key == 'notice' ? 'success' : 'danger' %> "> 
            <%= message %>
           </div>
         <% end %>
       </div>
    </div>
    <p class="notice"><%= notice %></p>                                                                │
    <p class="alert"><%= alert %></p> 
 